name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Matches version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies for build
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -U pip
        pip install build twine

    - name: Build package
      run: |
        source venv/bin/activate
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        source venv/bin/activate
        python -m twine upload dist/*
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*